### ISSUE TITLE
feasibility for a grpc implementation

### ISSUE THREAD

**Issue by tmc** [marwan-at-work/protoc-gen-twirpql#2]
Could you comment on the feasibility of having grpc (non-twirp) support?

**Comment by marwan-at-work** [comment]
@tmc for basic support, it should already work. Here's what's missing: 

1. Stream support (only server->client streaming, since GraphQL does not support the other way around AFAIK). 

2. Middleware support, we'd need to map gRPC unary interceptors to GraphQL resolver middlewares

**Comment by tmc** [comment]
Thanks.
